### ISSUE TITLE
ModuleNotFoundError: No module named 'ldm.ops'

### ISSUE THREAD

**Issue by 2snEM6** [nuanarchy/ComfyUI-NuA-FlashFace#5]
Hi! I installed these nodes using ComfyUI manager and upon loading the nodes, the following error occurs:

```python
Traceback (most recent call last):
  File "C:\Users\bumblebee\development\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\bumblebee\development\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NuA-FlashFace\__init__.py", line 1, in <module>
    from .flashface_loader import *
  File "C:\Users\bumblebee\development\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NuA-FlashFace\flashface_loader.py", line 4, in <module>
    from .flashfacelib.api import FlashFace
  File "C:\Users\bumblebee\development\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NuA-FlashFace\flashfacelib\api.py", line 20, in <module>
    from .flashface.ops.context_diffusion import ContextGaussianDiffusion
  File "C:\Users\bumblebee\development\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NuA-FlashFace\flashfacelib\flashface\ops\__init__.py", line 1, in <module>
    from .context_diffusion import *
  File "C:\Users\bumblebee\development\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NuA-FlashFace\flashfacelib\flashface\ops\context_diffusion.py", line 15, in <module>
    from ldm.ops.diffusion import GaussianDiffusion
ModuleNotFoundError: No module named 'ldm.ops'
```

I debugged what `content_diffusion` is importing from `ldm` module on this line:

https://github.com/nuanarchy/ComfyUI-NuA-FlashFace/blob/6ad38672123084b21bed23829558105dd76b26c9/flashfacelib/flashface/ops/context_diffusion.py#L6

And it seems it's not exporting `ops`? It exports just `modules` and `util`

I wonder if I did something wrong 🤔

Thank you

**Comment by nuanarchy** [comment]
I tested the code from the repository and from the ComfyUI Manager, everything works.

But it seems that you don't have the path to flashfacelib in PYTHONPATH. This is done automatically here:
https://github.com/nuanarchy/ComfyUI-NuA-FlashFace/blob/6ad38672123084b21bed23829558105dd76b26c9/flashfacelib/api.py#L3-L4
but in your case there may be a difference in versions or something.

Print the PYTHONPATH where you have a problem:
import sys
print(sys.path)

Also you can try this:
import os
package_dir = "abspath/to/flashfacelib"
sys.path.insert(0, package_dir)

**Comment by 2snEM6** [comment]
Thank you, still no luck. I have flashfacelib in the path. I will try with a fresh installation and see

**Comment by 2snEM6** [comment]
Using a fresh installation worked! Closing
